backend:
  name: git-gateway     # usa o Git Gateway do Netlify
  branch: main          # branch principal do repositório

media_folder: "public/uploads"   # ficheiros sob controlo do Git
public_folder: "/uploads"        # caminho público nos posts

collections:
  - name: "posts"
    label: "Publicações"
    folder: "public/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título",  name: "title", widget: "string" }
      - { label: "Data",    name: "date",  widget: "datetime" }
      - { label: "Conteúdo", name: "body", widget: "markdown" }
