
backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads"
public_folder: "/uploads"

collections:
  - name: "filmes"
    label: "Filmes"
    folder: "public/filmes"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Descrição", name: "body", widget: "text" }
      - { label: "Imagem (URL)", name: "imagem", widget: "string" }
      - { label: "Link de Visualização", name: "link", widget: "string" }
